version: "3.7"

services:
  my-postgres:
    container_name: db-bank
    build: "./database"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bank
    restart: always
    ports:
      - "5432:5432"

  pg-admin:
    container_name: pgadmin-db-bank
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: alexrondon89@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - my-postgres